# Generated by Django 3.1.7 on 2021-03-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faculdades_trabalhos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculdades',
            options={'verbose_name': 'Faculdade', 'verbose_name_plural': 'Faculdades'},
        ),
        migrations.AlterModelOptions(
            name='filmes',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='musicas',
            options={'verbose_name': 'Musica', 'verbose_name_plural': 'Musicas'},
        ),
        migrations.AlterModelOptions(
            name='mydescription',
            options={'verbose_name': 'My Description', 'verbose_name_plural': 'My Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='trabalhos',
            options={'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
        migrations.AlterModelOptions(
            name='viagens',
            options={'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
        migrations.AlterField(
            model_name='mydescription',
            name='idade',
            field=models.CharField(max_length=99),
        ),
    ]
